/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.util.Vector;

/**
 *
 * @author EnablePassword
 */
public class frmMain extends javax.swing.JFrame {

    Vector data = new Vector();
    public static boolean logined = false;
    public static int roleNumber;
    public static String currentUserLoggedIn;
    public static String currentPMLoggedIn;
    public static String currentHRLoggedIn;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        disableMenu();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnToolbarLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnToolbarExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniFileLogin = new javax.swing.JMenuItem();
        mniAddUser = new javax.swing.JMenuItem();
        mniFileExit = new javax.swing.JMenuItem();
        mnuMangament = new javax.swing.JMenu();
        mniEmployeeManage = new javax.swing.JMenuItem();
        mniProjectManage = new javax.swing.JMenuItem();
        mnuSearch = new javax.swing.JMenu();
        mniSearchEmployee = new javax.swing.JMenuItem();
        mniSearchTransferRecord = new javax.swing.JMenuItem();
        mnuTransfer = new javax.swing.JMenu();
        mniNewTransfer = new javax.swing.JMenuItem();
        mniTransferApproveTransfer = new javax.swing.JMenuItem();
        mniRequestLog = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        mniGenerateReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onlinelogomaker-031116-1208.png"))); // NOI18N

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        btnToolbarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Enter-48.png"))); // NOI18N
        btnToolbarLogin.setText("Login");
        btnToolbarLogin.setFocusable(false);
        btnToolbarLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolbarLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToolbarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(btnToolbarLogin);
        jToolBar1.add(jSeparator1);

        btnToolbarExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit Sign-48.png"))); // NOI18N
        btnToolbarExit.setText("Exit");
        btnToolbarExit.setFocusable(false);
        btnToolbarExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToolbarExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnToolbarExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnToolbarExit);

        mnuFile.setText("File");

        mniFileLogin.setText("Login");
        mniFileLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFileLoginActionPerformed(evt);
            }
        });
        mnuFile.add(mniFileLogin);

        mniAddUser.setText("Add User");
        mniAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddUserActionPerformed(evt);
            }
        });
        mnuFile.add(mniAddUser);

        mniFileExit.setText("Exit");
        mniFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFileExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniFileExit);

        jMenuBar1.add(mnuFile);

        mnuMangament.setText("Management");

        mniEmployeeManage.setText("Manage Employee");
        mniEmployeeManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmployeeManageActionPerformed(evt);
            }
        });
        mnuMangament.add(mniEmployeeManage);

        mniProjectManage.setText("Manage Project");
        mniProjectManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProjectManageActionPerformed(evt);
            }
        });
        mnuMangament.add(mniProjectManage);

        jMenuBar1.add(mnuMangament);

        mnuSearch.setText("Search");

        mniSearchEmployee.setText("Employee");
        mniSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSearchEmployeeActionPerformed(evt);
            }
        });
        mnuSearch.add(mniSearchEmployee);

        mniSearchTransferRecord.setText("Transfer Record");
        mniSearchTransferRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSearchTransferRecordActionPerformed(evt);
            }
        });
        mnuSearch.add(mniSearchTransferRecord);

        jMenuBar1.add(mnuSearch);

        mnuTransfer.setText("Transfer");
        mnuTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransferActionPerformed(evt);
            }
        });

        mniNewTransfer.setText("New Transfer");
        mniNewTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewTransferActionPerformed(evt);
            }
        });
        mnuTransfer.add(mniNewTransfer);

        mniTransferApproveTransfer.setText("Transfer Approval");
        mniTransferApproveTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTransferApproveTransferActionPerformed(evt);
            }
        });
        mnuTransfer.add(mniTransferApproveTransfer);

        mniRequestLog.setText("Transfer Request Logs");
        mniRequestLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRequestLogActionPerformed(evt);
            }
        });
        mnuTransfer.add(mniRequestLog);

        jMenuBar1.add(mnuTransfer);

        mnuReport.setText("Report");
        mnuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportActionPerformed(evt);
            }
        });

        mniGenerateReport.setText("Generate Report");
        mniGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGenerateReportActionPerformed(evt);
            }
        });
        mnuReport.add(mniGenerateReport);

        jMenuBar1.add(mnuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(583, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniFileLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFileLoginActionPerformed
        if (logined) {
            lblWelcome.setText("");
            mniFileLogin.setText("Login");
            btnToolbarLogin.setText("Login");
            logined = false;
            btnToolbarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Enter-48.png")));
            //JOptionPane.showMessageDialog(this, "You have been logged out.");
            disableMenu();
        } else {
            frmLogin frLogin = new frmLogin(this, true);
            frLogin.setVisible(true);
        }
    }//GEN-LAST:event_mniFileLoginActionPerformed

    private void disableMenu() {
        mniAddUser.setEnabled(false);
        mniEmployeeManage.setEnabled(false);
        mniSearchEmployee.setEnabled(false);
        mniSearchTransferRecord.setEnabled(false);
        mniGenerateReport.setEnabled(false);
        mniTransferApproveTransfer.setEnabled(false);
        mniNewTransfer.setEnabled(false);
        mniProjectManage.setEnabled(false);
        mniRequestLog.setEnabled(false);
    }


    private void mniEmployeeManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmployeeManageActionPerformed
        frmEmployeeManage empManage = new frmEmployeeManage(this, true);
        empManage.setVisible(true);
    }//GEN-LAST:event_mniEmployeeManageActionPerformed

    private void mniSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSearchEmployeeActionPerformed
        frmSearchEmployee searchEmp = new frmSearchEmployee(this, true);
        searchEmp.setVisible(true);
    }//GEN-LAST:event_mniSearchEmployeeActionPerformed

    private void mniSearchTransferRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSearchTransferRecordActionPerformed
        frmSearchTransferRecord frSearchTransferRecord = new frmSearchTransferRecord(this, true);
        frSearchTransferRecord.setVisible(true);
    }//GEN-LAST:event_mniSearchTransferRecordActionPerformed

    private void mnuTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransferActionPerformed
        //frmTransfer frTransfer = new frmTransfer(this, true);
        //frTransfer.setVisible(true);
    }//GEN-LAST:event_mnuTransferActionPerformed

    private void mniFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniFileExitActionPerformed

    private void mniAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddUserActionPerformed
        frmAddUser frAddUser = new frmAddUser(this, true);
        frAddUser.setVisible(true);
    }//GEN-LAST:event_mniAddUserActionPerformed

    private void mniNewTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewTransferActionPerformed
        frmRequestTransfer frRequestTransfer = new frmRequestTransfer(this, true);
        frRequestTransfer.setVisible(true);
    }//GEN-LAST:event_mniNewTransferActionPerformed

    private void mniTransferApproveTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTransferApproveTransferActionPerformed
        frmApproveTransfer approval = new frmApproveTransfer(this, true);
        approval.setVisible(true);
    }//GEN-LAST:event_mniTransferApproveTransferActionPerformed

    private void btnToolbarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarLoginActionPerformed
        mniFileLogin.doClick();
    }//GEN-LAST:event_btnToolbarLoginActionPerformed

    private void btnToolbarExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnToolbarExitActionPerformed

    private void mniTransferRequestLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTransferRequestLogActionPerformed
        frmRequestLog frRequestLog = new frmRequestLog(this, true);
        frRequestLog.setVisible(true);
    }//GEN-LAST:event_mniTransferRequestLogActionPerformed

    private void mnuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportActionPerformed
        
    }//GEN-LAST:event_mnuReportActionPerformed

    private void mniGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGenerateReportActionPerformed
        frmReportForm reportForm = new frmReportForm(this, true);
        reportForm.setVisible(true);
    }//GEN-LAST:event_mniGenerateReportActionPerformed

    private void mniProjectManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProjectManageActionPerformed
        frmManageProject manageProjectForm = new frmManageProject(this, true);
        manageProjectForm.setVisible(true);
    }//GEN-LAST:event_mniProjectManageActionPerformed

    private void mniRequestLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRequestLogActionPerformed
        frmRequestLog requestLogForm = new frmRequestLog(this, true);
        requestLogForm.setVisible(true);
    }//GEN-LAST:event_mniRequestLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToolbarExit;
    public static javax.swing.JButton btnToolbarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JLabel lblWelcome;
    public static javax.swing.JMenuItem mniAddUser;
    public static javax.swing.JMenuItem mniEmployeeManage;
    private javax.swing.JMenuItem mniFileExit;
    public static javax.swing.JMenuItem mniFileLogin;
    public static javax.swing.JMenuItem mniGenerateReport;
    public static javax.swing.JMenuItem mniNewTransfer;
    public static javax.swing.JMenuItem mniProjectManage;
    public static javax.swing.JMenuItem mniRequestLog;
    public static javax.swing.JMenuItem mniSearchEmployee;
    public static javax.swing.JMenuItem mniSearchTransferRecord;
    public static javax.swing.JMenuItem mniTransferApproveTransfer;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuMangament;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuSearch;
    public static javax.swing.JMenu mnuTransfer;
    // End of variables declaration//GEN-END:variables
}
